version: 0.2

# env:
#   variables:
#     FUNCTION_NAME: "github-to-lambda-demo"
#     S3_BUCKET: "my-deployment-bucket-fabio"
#     ZIP_FILE: "github-to-lambda-demo.zip"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm install
    
  pre_build:
    commands:
      - echo "Running pre build commands"

  build:
    commands:
      - echo "Zipping the lambda function"
      - zip -r github-to-lambda-demo.zip .
      # - zip -r ${ZIP_FILE} . -x '*.git*' 'node_modules/aws-sdk/*'

  post_build:
    commands:
      - echo "Post-build - Uploading to S3"
      - aws s3 cp github-to-lambda-demo.zip s3://my-deployment-bucket-fabio/github-to-lambda-demo.zip
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name github-to-lambda-demo --s3-bucket my-deployment-bucket-fabio --s3-key github-to-lambda-demo.zip

artifacts:
  files:
    - github-to-lambda-demo.zip