version: 0.2

# env:
#   variables:
#     FUNCTION_NAME: "github-to-lambda-demo"
#     S3_BUCKET: "my-deployment-bucket-fabio"
#     ZIP_FILE: "github-to-lambda-demo.zip"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm install
    
  pre_build:
    commands:
      - echo "Running pre build commands"
      - npm run test

  build:
    commands:
      - echo "Zipping the lambda function"
      - zip -r ${ZIP_FILE} . -x '*.git*' 'node_modules/*'

  post_build:
    commands:
      - echo "Post-build - Uploading to S3"
      - aws s3 cp ${ZIP_FILE} s3://${S3_BUCKET}/${ZIP_FILE}
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name ${FUNCTION_NAME} --s3-bucket ${S3_BUCKET} --s3-key ${ZIP_FILE}

artifacts:
  files:
    - ${ZIP_FILE}